name: Log group
on: 
    workflow_dispatch:
jobs:
    logs:
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo "::group::Show enviroment variables"
                printenv
                echo "::endgroup::"